# Generated by Django 3.1.1 on 2020-10-06 16:02

import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to=demo.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_caption',
            field=models.CharField(default='', max_length=100),
        ),
    ]
